/**
 * What an audit action did, said for a person: "inventory.auto_roll" reads
 * "Renewal date rolled forward". Used where a page shows recent changes to
 * someone who did not come to query the log (Home's recent changes); Audit
 * itself keeps the raw names, since they are what its query tokens match.
 *
 * Only actions lattice-server records (e596325) and a person would care to
 * read are listed; an action not listed keeps its raw name, which is honest
 * and still searchable. Every label keeps the raw action beside it.
 *
 * Framework-free: a view resolves the returned key through i18n.
 */

export const AUDIT_ACTION_KEY_PREFIX = "operations.audit.actions";

/** Actions with a label of their own. The key is the action in camelCase. */
export const LABELLED_AUDIT_ACTIONS: ReadonlySet<string> = new Set([
  "approval.auto_approve",
  "approval.auto_skip",
  "network.apply",
  "plugin.operation.plan",
  "plugin.operation.execute",
  "plugin.operation.applied",
  "plugin.operation.failed",
  "plugin.loaded",
  "plugin.rejected",
  "task.create",
  "task.cancel",
  "task.delete",
  "task.rerun",
  "task.result",
  "task.script.reveal",
  "inventory.create",
  "inventory.update",
  "inventory.delete",
  "inventory.renew",
  "inventory.auto_roll",
  "inventory.reminder",
  "inventory.reminder.manual",
  "inventory.link.reveal",
  "inventory.vendor.upsert",
  "inventory.vendor.delete",
  "node.enroll",
  "node.delete",
  "node.update",
  "node.disable",
  "node.enable",
  "node.token.rotate",
  "node.geo.update",
  "node.geo.clear",
  "node.geo.resolve",
  "node.debug.update",
  "node.ip.config",
  "node.reconfigure.command",
  "node.terminal.transport",
  "group.create",
  "group.update",
  "group.delete",
  "group.members",
  "group.reorder",
  "group.seed",
  "group.policy.create",
  "group.policy.update",
  "group.policy.delete",
  "group.policy.plan",
  "agent.update.plan",
  "agent.update.applied",
  "agent.update.policy",
  "agent.update.policy.delete",
  "agent.artifact.import",
  "agent.artifact.put",
  "agent.artifact.delete",
  "agent.artifact.authorize",
  "linemeta.sync",
  "linemeta.sync.applied",
  "linemeta.sync.failed",
  "linechain.plan",
  "linechain.approve",
  "linechain.apply",
  "linechain.failed",
  "linechain.remove",
  "network.lines.managed_rollout",
  "network.lines.managed_rollout.applied",
  "network.lines.managed_rollout.failed",
  "network.lines.managed_rollout.stale_result",
  "vpnuser.line.plan",
  "vpnuser.line.applied",
  "vpnuser.line.failed",
  "vpnuser.line.stale_result",
  "vpnuser.credential.rotate",
  "vpn.user.credentials.reveal",
  "vpn-core.profile.configure",
  "line.uuid.reattach",
  "singbox.manage.add",
  "singbox.manage.delete",
  "singbox.manage.users",
  "singbox.line.reveal",
  "substore.autosync",
  "proxy.plan",
  "proxy.apply.applied",
  "proxy.apply.failed",
  "proxy.config.drift",
  "proxy.user.upsert",
  "proxy.user.delete",
  "proxy.user.rotate_sub_token",
  "proxy.profile.upsert",
  "proxy.profile.delete",
  "proxy.inbound.upsert",
  "proxy.inbound.delete",
  "dns.plan",
  "dns.apply.applied",
  "dns.apply.failed",
  "dns.publish",
  "dns.deployment.upsert",
  "dns.deployment.delete",
  "dns.lockout_risk.accepted",
  "ddns.create",
  "ddns.update",
  "ddns.delete",
  "ddns.run",
  "geo.routing.upsert",
  "geo.routing.delete",
  "geo.routing.plan",
  "netguard.plan",
  "netguard.apply.applied",
  "netguard.apply.failed",
  "netguard.zone.upsert",
  "netguard.zone.delete",
  "netguard.group.upsert",
  "netguard.group.delete",
  "netguard.binding.upsert",
  "netguard.binding.delete",
  "netguard.node.adopt",
  "netguard.lockout_risk.accepted",
  "network.nft.plan",
  "network.nft.inputs.upsert",
  "network.nft.inputs.delete",
  "network.nft.lockout_risk.accepted",
  "network.policy.upsert",
  "network.policy.delete",
  "network.policy.plan",
  "network.policy.applied",
  "network.policy.failed",
  "network.wireguard.plan",
  "sshguard.plan",
  "sshguard.confirm.plan",
  "sshguard.findings.accepted",
  "sshguard.knock.reveal",
  "tunnel.create",
  "tunnel.delete",
  "tunnel.plan",
  "monitor.create",
  "monitor.delete",
  "notify.channel.create",
  "notify.channel.update",
  "notify.channel.delete",
  "notify.rule.upsert",
  "notify.rule.delete",
  "notify.test",
  "notify.webhook.create",
  "notify.webhook.update",
  "notify.webhook.delete",
  "notify.webhook.rotate",
  "notify.webhook.test",
  "token.create",
  "token.revoke",
  "token.delete",
  "user.create",
  "user.update",
  "user.delete",
  "auth.password.change",
  "2fa.enroll",
  "2fa.activate",
  "2fa.disable",
  "webauthn.register",
  "webauthn.rename",
  "webauthn.delete",
  "login.oidc",
  "login.totp",
  "login.totp.recovery_used",
  "login.webauthn",
  "security.step_up",
  "security.step_up.webauthn",
  "ssh.login",
  "oidc.provider.upsert",
  "oidc.provider.delete",
  "oidc.provider.test",
  "storage.bucket.upsert",
  "storage.token.create",
  "storage.token.revoke",
  "storage.binding.upsert",
  "storage.binding.delete",
  "kv.put",
  "kv.delete",
  "static.put",
  "static.delete",
  "terminal.open",
  "terminal.attach",
  "terminal.close",
  "terminal.agent.close",
  "terminal.reaper.close",
  "capability.policy",
  "trace.policy.set",
  "trace.session.start",
  "trace.session.stop",
  "log.source.create",
  "log.source.update",
  "log.source.delete",
  "log.source.enable",
  "log.source.disable",
] as const);

/** "network.<plugin>.approve" and its siblings: an approval decision on any plugin's plan. */
const PLAN_DECISION = /^network\..+\.(approve|reject|dismiss)$/;

/** The camelCase key of an action: "inventory.auto_roll" is "inventoryAutoRoll"; "2fa." reads "twoFactor". */
export function auditActionKeyName(action: string): string {
  const parts = action.replace(/^2fa/, "twoFactor").split(/[._-]/).filter(Boolean);
  return parts.map((part, index) => (index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1))).join("");
}

/** The i18n key of an action's label, or null when it has none and keeps its raw name. */
export function auditActionLabelKey(action: string): string | null {
  const name = action.trim();
  const decision = PLAN_DECISION.exec(name);
  if (decision?.[1]) {
    const verb = decision[1];
    return `${AUDIT_ACTION_KEY_PREFIX}.networkPlan${verb.charAt(0).toUpperCase()}${verb.slice(1)}`;
  }
  if (!LABELLED_AUDIT_ACTIONS.has(name)) return null;
  return `${AUDIT_ACTION_KEY_PREFIX}.${auditActionKeyName(name)}`;
}
